### ISSUE TITLE
Cambiare il modo di indirizzare gli utenti

### ISSUE THREAD

**Issue by Fileini** [RengaPD/progetto2#2]
Dobbiamo cambiare il codice, gli utenti vanno identificati con il loro id utente che è la chiave primaria nel database, nome e cognome non vanno bene, qualche modifica l'ho gia fatta io e probabilmente renderà non funzionante qualcosa

**Comment by SaraAbb** [comment]
Per il blog secondo me dobbiamo continuare ad usare nome e cognome dell'autore del post, l'id utente non significa nulla. L'id nella tabella blog serve solo come chiave univoca, ma non puoi sapere solo con quella se un post è di un blog o di un altro e quindi quale selezionare, con il nome dell'autore si.

**Comment by Fileini** [comment]
RISOLTO
